# Generated by Django 2.0.4 on 2018-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('inp_broker', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('standard_broker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('inp_head', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('out_head', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('inp_ticker', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('standard_ticker', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('prim_key', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('transtype', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('tradedate', models.DateField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, max_length=150, null=True)),
                ('shareamount', models.IntegerField(blank=True, null=True)),
                ('buyprice', models.FloatField(blank=True, null=True)),
                ('sellprice', models.FloatField(blank=True, null=True)),
                ('commiss', models.FloatField(blank=True, null=True)),
                ('dealsize', models.FloatField(blank=True, null=True)),
                ('dealprice', models.FloatField(blank=True, null=True)),
                ('leadbroker', models.CharField(blank=True, max_length=150, null=True)),
                ('percsellhold', models.FloatField(blank=True, null=True)),
                ('opentraddat', models.DateField(blank=True, null=True)),
                ('vwaptraddat', models.DateField(blank=True, null=True)),
                ('closetraddat', models.DateField(blank=True, null=True)),
                ('prevclose', models.FloatField(blank=True, null=True)),
                ('t2close', models.FloatField(blank=True, null=True)),
                ('t3close', models.FloatField(blank=True, null=True)),
                ('t4close', models.FloatField(blank=True, null=True)),
                ('t5close', models.FloatField(blank=True, null=True)),
                ('spopen', models.FloatField(blank=True, null=True)),
                ('spclose', models.FloatField(blank=True, null=True)),
                ('matching', models.CharField(blank=True, max_length=1000, null=True)),
                ('matching_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
