# Generated by Django 2.0.4 on 2018-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='matching_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shareamount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
